# SPDX-License-Identifier: GPL-2.0
#
# Makefile for the PHY drivers.
#

phy-dw-hdmi-e40x-y			:= phy-dw-hdmi-e40x-core.o
phy-dw-hdmi-e40x-y			+= phy-dw-hdmi-e405.o
phy-dw-hdmi-e40x-y			+= phy-dw-hdmi-e406.o
obj-$(CONFIG_VIDEO_DWC_HDMI_PHY_E40X)	+= phy-dw-hdmi-e40x.o
