# SPDX-License-Identifier: GPL-2.0
#
# Makefile for Parallel port IDE device drivers.
#
# 7 October 2000, Bartlomiej Zolnierkiewicz <bkz@linux-ide.org>
# Rewritten to use lists instead of if-statements.
#

obj-$(CONFIG_PATA_PARPORT)		+= pata_parport.o
obj-$(CONFIG_PATA_PARPORT_ATEN)		+= aten.o
obj-$(CONFIG_PATA_PARPORT_BPCK)		+= bpck.o
