# SPDX-License-Identifier: GPL-2.0
#
# Makefile for Parallel port IDE device drivers.
#
# 7 October 2000, Bartlomiej Zolnierkiewicz <bkz@linux-ide.org>
# Rewritten to use lists instead of if-statements.
#

obj-$(CONFIG_PATA_PARPORT)		+= pata_parport.o
obj-$(CONFIG_PATA_PARPORT_ATEN)		+= aten.o
obj-$(CONFIG_PATA_PARPORT_BPCK)		+= bpck.o
obj-$(CONFIG_PATA_PARPORT_BPCK6)	+= bpck6.o
obj-$(CONFIG_PATA_PARPORT_COMM)		+= comm.o
obj-$(CONFIG_PATA_PARPORT_DSTR)		+= dstr.o
obj-$(CONFIG_PATA_PARPORT_FIT2)		+= fit2.o
obj-$(CONFIG_PATA_PARPORT_FIT3)		+= fit3.o
obj-$(CONFIG_PATA_PARPORT_EPAT)		+= epat.o
obj-$(CONFIG_PATA_PARPORT_EPIA)		+= epia.o
obj-$(CONFIG_PATA_PARPORT_FRIQ)		+= friq.o
obj-$(CONFIG_PATA_PARPORT_FRPW)		+= frpw.o
obj-$(CONFIG_PATA_PARPORT_KBIC)		+= kbic.o
