# SPDX-License-Identifier: GPL-2.0-only
snd-ar-objs := audioreach.o q6apm.o topology.o
snd-apm-dai-objs := q6apm-dai.o
snd-apm-bedai-objs := q6apm-bedai.o

obj-$(CONFIG_SND_SOC_QCOM_AUDIOREACH) += snd-ar.o
obj-$(CONFIG_SND_SOC_QCOM_APM_DAI) += snd-apm-dai.o
obj-$(CONFIG_SND_SOC_QCOM_APM_BEDAI) += snd-apm-bedai.o


