# SPDX-License-Identifier: GPL-2.0

imx-dpu-drm-objs := dpu-constframe.o dpu-core.o dpu-crtc.o \
		    dpu-disengcfg.o dpu-dprc.o dpu-drv.o dpu-extdst.o \
		    dpu-fetchdecode.o dpu-fetcheco.o dpu-fetchlayer.o \
		    dpu-fetchwarp.o dpu-fetchunit.o dpu-framegen.o \
		    dpu-gammacor.o dpu-hscaler.o dpu-kms.o dpu-layerblend.o \
		    dpu-plane.o dpu-prg.o dpu-tcon.o dpu-vscaler.o

obj-$(CONFIG_DRM_IMX_DPU) += imx-dpu-drm.o
