# # SPDX-License-Identifier: MIT
#
# Makefile for ultrasoc drivers.
#

obj-$(CONFIG_ULTRASOC) += ultrasoc-drv.o
ultrasoc-drv-objs := ultrasoc.o

obj-$(CONFIG_ULTRASOC_AXI_COM) += ultrasoc-axi-com-drv.o
ultrasoc-axi-com-drv-objs := ultrasoc-axi-com.o

obj-$(CONFIG_ULTRASOC_SMB) += ultrasoc-smb-drv.o
ultrasoc-smb-drv-objs := ultrasoc-smb.o
