#!/usr/bin/env python3
# SPDX-License-Identifier: GPL-2.0-only
#
# dot2m: transform dot files into C structures.
# For more information, see:
#   https://bristot.me/efficient-formal-verification-for-the-linux-kernel/
#
# This program was written in the development of this paper:
#  de Oliveira, D. B. and Cucinotta, T. and de Oliveira, R. S.
#  "Efficient Formal Verification for the Linux Kernel." International
#  Conference on Software Engineering and Formal Methods. Springer, Cham, 2019.
#
# Copyright 2018-2020 Red Hat, Inc.
#
# Author:
#  Daniel Bristot de Oliveira <bristot@kernel.org>

if __name__ == '__main__':
    from dot2 import dot2c
    import argparse
    import ntpath
    import sys

    parser = argparse.ArgumentParser(description='dot2c: converts a .dot file into a C structure')
    parser.add_argument('dot_file',  help='The dot file to be converted')


    args = parser.parse_args()
    d=dot2c.Dot2c(args.dot_file)
    d.print_model_classic()
