/* SPDX-License-Identifier: GPL-2.0 */
#ifndef _ASM_PPC_TRAPS_H
#define _ASM_PPC_TRAPS_H

#if defined(CONFIG_BOOKE) || defined(CONFIG_4xx)
#define INTERRUPT_MACHINE_CHECK   0x000
#define INTERRUPT_CRITICAL_INPUT  0x100
#define INTERRUPT_ALTIVEC_UNAVAIL 0x200
#define INTERRUPT_PERFMON         0x260
#define INTERRUPT_DOORBELL        0x280
#define INTERRUPT_DEBUG           0xd00
#elif defined(CONFIG_PPC_BOOK3S)
#define INTERRUPT_SYSTEM_RESET    0x100
#define INTERRUPT_MACHINE_CHECK   0x200
#define INTERRUPT_DATA_SEGMENT    0x380
#define INTERRUPT_INST_SEGMENT    0x480
#define INTERRUPT_DOORBELL        0xa00
#define INTERRUPT_TRACE           0xd00
#define INTERRUPT_H_DATA_STORAGE  0xe00
#define INTERRUPT_PERFMON         0xf00
#define INTERRUPT_H_FAC_UNAVAIL   0xf80
#endif

#define INTERRUPT_DATA_STORAGE    0x300
#define INTERRUPT_INST_STORAGE    0x400
#define INTERRUPT_ALIGNMENT       0x600
#define INTERRUPT_PROGRAM         0x700
#define INTERRUPT_FP_UNAVAIL      0x800
#define INTERRUPT_DECREMENTER     0x900
#define INTERRUPT_SYSCALL         0xc00

#endif /* _ASM_PPC_TRAPS_H */
