# SPDX-License-Identifier: GPL-2.0
#
# Makefile for drivers/platform/x86/intel
# Intel x86 Platform-Specific Drivers
#

intel_scu_ipc-y					:= ipc.o
obj-$(CONFIG_INTEL_SCU_IPC)		+= intel_scu_ipc.o
intel_scu_pcidrv-y				:= pcidrv.o
obj-$(CONFIG_INTEL_SCU_PCI)		+= intel_scu_pcidrv.o
intel_scu_pltdrv-y 				:= pltdrv.o
obj-$(CONFIG_INTEL_SCU_PLATFORM)	+= intel_scu_pltdrv.o
intel_scu_wdt-y					:= wdt.o
obj-$(CONFIG_INTEL_SCU_WDT)		+= intel_scu_wdt.o
intel_scu_ipcutil-y				:= ipcutil.o
obj-$(CONFIG_INTEL_SCU_IPC_UTIL)	+= intel_scu_ipcutil.o
