/* SPDX-License-Identifier: (GPL-2.0 OR MIT) */
/*
 *  Copyright (C) 2021 Adrien Grassein <adrien.grassein@gmail.com>
 */

#ifndef __DT_BINDINGS_IMX8MP_POWER_H__
#define __DT_BINDINGS_IMX8MP_POWER_H__

#define IMX8MP_POWER_DOMAIN_HSIOMIX	0
#define IMX8MP_POWER_DOMAIN_PCIE1	1
#define IMX8MP_POWER_DOMAIN_USB_OTG1	2
#define IMX8MP_POWER_DOMAIN_USB_OTG2	3
#define IMX8MP_POWER_DOMAIN_MLMIX	4
#define IMX8MP_POWER_DOMAIN_AUDIOMIX	5
#define IMX8MP_POWER_DOMAIN_GPU_MIX	6
#define IMX8MP_POWER_DOMAIN_GPU_2D	7
#define IMX8MP_POWER_DOMAIN_GPU_3D	8
#define IMX8MP_POWER_DOMAIN_VPUMIX	9
#define IMX8MP_POWER_DOMAIN_G1		10
#define IMX8MP_POWER_DOMAIN_G2		11
#define IMX8MP_POWER_DOMAIN_H1		12
#define IMX8MP_POWER_MEDIAMIX		13
#define IMX8MP_ISP_DWP			14
#define IMX8MP_MIPI_PHY1		15
#define IMX8MP_MIPI_PHY2		16
#define IMX8MP_HDMI_MIX			17
#define IMX8MP_HDMI_PHY			18
#endif
