/* SPDX-License-Identifier: (GPL-2.0 OR MIT) */
/*
 *  Copyright (C) 2021 Adrien Grassein <adrien.grassein@gmail.com>
 */

#ifndef __DT_BINDINGS_IMX8MM_POWER_H__
#define __DT_BINDINGS_IMX8MM_POWER_H__

#define IMX8MM_POWER_DOMAIN_HSIOMIX	0
#define IMX8MM_POWER_DOMAIN_PCIE1	1
#define IMX8MM_POWER_DOMAIN_USB_OTG1	2
#define IMX8MM_POWER_DOMAIN_USB_OTG2	3
#define IMX8MM_POWER_DOMAIN_GPU		4
#define IMX8MM_POWER_DOMAIN_VPU		5
#define IMX8MM_POWER_DOMAIN_VPU_G1	6
#define IMX8MM_POWER_DOMAIN_VPU_G2	7
#define IMX8MM_POWER_DOMAIN_VPU_H1	8
#define IMX8MM_POWER_DOMAIN_DISPLAY	9
#define IMX8MM_POWER_DOMAIN_MIPI	10

#endif
