# SPDX-License-Identifier: GPL-2.0
CFLAGS := -static -I../../../../usr/include

TEST_PROGS := run_empty.sh
TEST_GEN_FILES := init empty
TEST_FILES := lib.sh

include ../lib.mk

EXTRA_CLEAN := initrd cpio_list
