# SPDX-License-Identifier: GPL-2.0
#
# Makefile for the Sunplus Pin control drivers.
#
obj-$(CONFIG_PINCTRL_SPPCTL) += sppctl.o
obj-$(CONFIG_PINCTRL_SPPCTL) += sppctl_pinctrl.o
obj-$(CONFIG_PINCTRL_SPPCTL) += sppctl_sysfs.o
obj-$(CONFIG_PINCTRL_SPPCTL) += sppctl_gpio_ops.o
obj-$(CONFIG_PINCTRL_SPPCTL) += sppctl_gpio.o
obj-$(CONFIG_PINCTRL_SPPCTL) += pinctrl_inf_sp7021.o
obj-$(CONFIG_PINCTRL_SPPCTL) += gpio_inf_sp7021.o
