/* SPDX-License-Identifier: GPL-2.0 */
/*
 * Copyright (c) 2018 - present Synopsys, Inc. and/or its affiliates.
 * Synopsys DesignWare HDMI Receiver controller driver
 *
 * Author: Jose Abreu <jose.abreu@synopsys.com>
 * Author: Nelson Costa <nelson.costa@synopsys.com>
 */

#ifndef __DW_HDMI_RX_H__
#define __DW_HDMI_RX_H__

#include <linux/bitops.h>

/* id_hdmi Registers */
#define DW_HDMI_SETUP_CTRL			0x0000
#define DW_HDMI_HOT_PLUG_DETECT_INPUT_X_MASK	GENMASK(27, 24)
#define DW_HDMI_HOT_PLUG_DETECT_INPUT_X_OFFSET	24
#define DW_HDMI_HDMIBUS_RESET_OVR_EN_MASK	BIT(21)
#define DW_HDMI_HDMIBUS_RESET_OVR_EN_OFFSET	21
#define DW_HDMI_BUS_RESET_OVR_MASK		BIT(20)
#define DW_HDMI_BUS_RESET_OVR_OFFSET		20
#define DW_HDMI_HDMI_RESET_OVR_MASK		BIT(19)
#define DW_HDMI_HDMI_RESET_OVR_OFFSET		19
#define DW_HDMI_PON_RESET_OVR_MASK		BIT(18)
#define DW_HDMI_PON_RESET_OVR_OFFSET		18
#define DW_HDMI_RESET_OVR_MASK			BIT(17)
#define DW_HDMI_RESET_OVR_OFFSET		17
#define DW_HDMI_RESET_OVR_EN_MASK		BIT(16)
#define DW_HDMI_RESET_OVR_EN_OFFSET		16
#define DW_HDMI_EQ_OSM_OVR_MASK			BIT(15)
#define DW_HDMI_EQ_OSM_OVR_OFFSET		15
#define DW_HDMI_EQ_OSM_OVR_EN_MASK		BIT(14)
#define DW_HDMI_EQ_OSM_OVR_EN_OFFSET		14
#define DW_HDMI_NOWAIT_ACTIVITY_MASK		BIT(13)
#define DW_HDMI_NOWAIT_ACTIVITY_OFFSET		13
#define DW_HDMI_EQ_CAL_TIME_MASK		GENMASK(12, 7)
#define DW_HDMI_EQ_CAL_TIME_OFFSET		7
#define DW_HDMI_USE_PLL_LOCK_MASK		BIT(6)
#define DW_HDMI_USE_PLL_LOCK_OFFSET		6
#define DW_HDMI_FORCE_STATE_MASK		BIT(5)
#define DW_HDMI_FORCE_STATE_OFFSET		5
#define DW_HDMI_TARGET_STATE_MASK		GENMASK(4, 1)
#define DW_HDMI_TARGET_STATE_OFFSET		1
#define DW_HDMI_HOT_PLUG_DETECT_MASK		BIT(0)
#define DW_HDMI_HOT_PLUG_DETECT_OFFSET		0

#define DW_HDMI_PLL_LCK_STS			0x0030
#define DW_HDMI_PLL_LOCKED			BIT(0)

#define DW_HDMI_MODE_RECOVER			0x0080
#define DW_HDMI_SPIKE_FILTER_EN_MASK		BIT(18)
#define DW_HDMI_SPIKE_FILTER_EN_OFFSET		18
#define DW_HDMI_DVI_MODE_HYST_MASK		GENMASK(17, 13)
#define DW_HDMI_DVI_MODE_HYST_OFFSET		13
#define DW_HDMI_HDMI_MODE_HYST_MASK		GENMASK(12, 8)
#define DW_HDMI_HDMI_MODE_HYST_OFFSET		8

#define DW_HDMI_CKM_EVLTM			0x0094
#define DW_HDMI_LOCK_HYST_MASK			GENMASK(21, 20)
#define DW_HDMI_LOCK_HYST_OFFSET		20
#define DW_HDMI_CLK_HYST_MASK			GENMASK(18, 16)
#define DW_HDMI_CLK_HYST_OFFSET			16
#define DW_HDMI_EVAL_TIME_MASK			GENMASK(15, 4)
#define DW_HDMI_EVAL_TIME_OFFSET		4
#define DW_HDMI_CLK_MEAS_INPUT_SRC_MASK		BIT(0)
#define DW_HDMI_CLK_MEAS_INPUT_SRC_OFFSET	0

#define DW_HDMI_CKM_RESULT			0x009c
#define DW_HDMI_CLOCK_IN_RANGE			BIT(17)
#define DW_HDMI_FREQ_LOCKED			BIT(16)
#define DW_HDMI_CLKRATE_MASK			GENMASK(15, 0)
#define DW_HDMI_CLKRATE_OFFSET			0

#define DW_HDMI_VM_CFG_CH_0_1			0x00b0
#define DW_HDMI_VM_CH1_COL_VALUE_MASK		GENMASK(31, 16)
#define DW_HDMI_VM_CH1_COL_VALUE_OFFSET		16
#define DW_HDMI_VM_CH0_COL_VALUE_MASK		GENMASK(15, 0)
#define DW_HDMI_VM_CH0_COL_VALUE_OFFSET		0

#define DW_HDMI_VM_CFG_CH2			0x00b4
#define DW_HDMI_VM_CH2_COL_VALUE_MASK		GENMASK(15, 0)
#define DW_HDMI_VM_CH2_COL_VALUE_OFFSET		0

#define DW_HDMI_STS				0x00bc
#define DW_HDMI_DCM_CURRENT_MODE_MASK		GENMASK(31, 28)
#define DW_HDMI_DCM_CURRENT_MODE_OFFSET		28
#define DW_HDMI_DCM_LAST_PIXEL_PHASE_STS_MASK	GENMASK(27, 24)
#define DW_HDMI_DCM_LAST_PIXEL_PHASE_STS_OFFSET	24
#define DW_HDMI_DCM_PHASE_DIFF_CNT_MASK		GENMASK(23, 16)
#define DW_HDMI_DCM_PH_DIFF_CNT_OVERFL		BIT(15)
#define DW_HDMI_DCM_GCP_ZERO_FIELDS_PASS	BIT(14)
#define DW_HDMI_CTL3_STS			BIT(13)
#define DW_HDMI_CTL2_STS			BIT(12)
#define DW_HDMI_CTL1_STS			BIT(11)
#define DW_HDMI_CTL0_STS			BIT(10)
#define DW_HDMI_VS_POL_ADJ_STS			BIT(9)
#define DW_HDMI_HS_POL_ADJ_STS			BIT(8)
#define DW_HDMI_RES_OVERLOAD_STS		BIT(7)
#define DW_HDMI_DCM_CURRENT_PP_MASK		GENMASK(3, 0)
#define DW_HDMI_DCM_CURRENT_PP_OFFSET		0

/* id_hdcp_1_4 Registers */
#define DW_HDMI_HDCP_CTRL			0x00c0
#define DW_HDMI_HDCP_STS			0x00fc

/* id_mode_detection Registers */
#define DW_HDMI_MD_HT0				0x0148
#define DW_HDMI_HTOT32_CLK_MASK			GENMASK(31, 16)
#define DW_HDMI_HTOT32_CLK_OFFSET		16
#define DW_HDMI_HS_CLK_MASK			GENMASK(15, 0)
#define DW_HDMI_HS_CLK_OFFSET			0

#define DW_HDMI_MD_HT1				0x014c
#define DW_HDMI_HTOT_PIX_MASK			GENMASK(31, 16)
#define DW_HDMI_HTOT_PIX_OFFSET			16
#define DW_HDMI_HOFS_PIX_MASK			GENMASK(15, 0)
#define DW_HDMI_HOFS_PIX_OFFSET			0

#define DW_HDMI_MD_HACT_PX			0x0150

#define DW_HDMI_MD_VCTRL			0x0158
#define DW_HDMI_V_OFFS_LIN_MODE_MASK		BIT(4)
#define DW_HDMI_V_OFFS_LIN_MODE_OFFSET		4
#define DW_HDMI_V_EDGE_MASK			BIT(1)
#define DW_HDMI_V_EDGE_OFFSET			1
#define DW_HDMI_V_MODE_MASK			BIT(0)
#define DW_HDMI_V_MODE_OFFSET			0

#define DW_HDMI_MD_VOL				0x0164
#define DW_HDMI_MD_VAL				0x0168
#define DW_HDMI_MD_VTL				0x0170

#define DW_HDMI_MD_STS				0x0180
#define DW_HDMI_ILACE_STS			BIT(3)
#define DW_HDMI_DE_ACTIVITY_STS			BIT(2)
#define DW_HDMI_VS_ACT_STS			BIT(1)
#define DW_HDMI_HS_ACT_STS			BIT(0)

/* id_phy_configuration Registers */
#define DW_HDMI_PHY_CTRL			0x02c0
#define DW_HDMI_PHYSVSRETMODEZ_MASK		BIT(6)
#define DW_HDMI_PHYSVSRETMODEZ_OFFSET		6
#define DW_HDMI_CFGCLKFREQ_MASK			GENMASK(5, 4)
#define DW_HDMI_CFGCLKFREQ_OFFSET		4
#define DW_HDMI_PORTSELECT_MASK			GENMASK(3, 2)
#define DW_HDMI_PORTSELECT_OFFSET		2
#define DW_HDMI_PHYPDDQ_MASK			BIT(1)
#define DW_HDMI_PHYPDDQ_OFFSET			1
#define DW_HDMI_PHYRESET_MASK			BIT(0)
#define DW_HDMI_PHYRESET_OFFSET			0

#define DW_HDMI_JTAG_CONF			0x02ec
#define DW_HDMI_JTAG_TAP_TCLK			0x02f0

#define DW_HDMI_JTAG_TAP_IN			0x02f4
#define DW_HDMI_JTAG_TMS			BIT(4)
#define DW_HDMI_JTAG_TDI			BIT(0)

#define DW_HDMI_JTAG_TAP_OUT			0x02f8
#define DW_HDMI_JTAG_ADDR			0x02fc

/* id_packet_decoder Registers */
#define DW_HDMI_PDEC_CTRL			0x0300
#define DW_HDMI_PFIFO_STORE_FILTER_EN_MASK	BIT(31)
#define DW_HDMI_PFIFO_STORE_FILTER_EN_OFFSET	31
#define DW_HDMI_PD_FIFO_CLR_MASK		BIT(5)
#define DW_HDMI_PD_FIFO_CLR_OFFSET		5
#define DW_HDMI_PDEC_BCH_EN_MASK		BIT(0)
#define DW_HDMI_PDEC_BCH_EN_OFFSET		0

#define DW_HDMI_PDEC_ACRM_CTRL			0x0330
#define DW_HDMI_DELTACTS_IRQTRIG_MASK		GENMASK(4, 2)
#define DW_HDMI_DELTACTS_IRQTRIG_OFFSET		2

#define DW_HDMI_PDEC_ASP_CTRL			0x0340
#define DW_HDMI_AUTO_VMUTE_MASK			BIT(6)
#define DW_HDMI_AUTO_VMUTE_OFFSET		6
#define DW_HDMI_AUTO_SPFLAT_MUTE_MASK		GENMASK(5, 2)
#define DW_HDMI_AUTO_SPFLAT_MUTE_OFFSET		2

#define DW_HDMI_PDEC_STS			0x0360
#define DW_HDMI_DRM_CKS_CHG			BIT(31)
#define DW_HDMI_DRM_RCV				BIT(30)
#define DW_HDMI_NTSCVBI_CKS_CHG			BIT(29)
#define DW_HDMI_DVIDET				BIT(28)
#define DW_HDMI_VSI_CKS_CHG			BIT(27)
#define DW_HDMI_GMD_CKS_CHG			BIT(26)
#define DW_HDMI_AIF_CKS_CHG			BIT(25)
#define DW_HDMI_AVI_CKS_CHG			BIT(24)
#define DW_HDMI_ACR_N_CHG			BIT(23)
#define DW_HDMI_ACR_CTS_CHG			BIT(22)
#define DW_HDMI_GCP_AV_MUTE_CHG			BIT(21)
#define DW_HDMI_GMD_RCV				BIT(20)
#define DW_HDMI_AIF_RCV				BIT(19)
#define DW_HDMI_AVI_RCV				BIT(18)
#define DW_HDMI_ACR_RCV				BIT(17)
#define DW_HDMI_GCP_RCV				BIT(16)
#define DW_HDMI_VSI_RCV				BIT(15)
#define DW_HDMI_AMP_RCV				BIT(14)
#define DW_HDMI_NTSCVBI_RCV			BIT(13)
#define DW_HDMI_OBA_LAYOUT			BIT(12)
#define DW_HDMI_AUDS_LAYOUT			BIT(11)
#define DW_HDMI_PD_FIFO_NEW_ENTRY		BIT(8)
#define DW_HDMI_PD_FIFO_OVERFL			BIT(4)
#define DW_HDMI_PD_FIFO_UNDERFL			BIT(3)
#define DW_HDMI_PD_FIFO_TH_START_PASS		BIT(2)
#define DW_HDMI_PD_FIFO_TH_MAX_PASS		BIT(1)
#define DW_HDMI_PD_FIFO_TH_MIN_PASS		BIT(0)

#define DW_HDMI_PDEC_VSI_PAYLOAD0		0x0368
#define DW_HDMI_VSI_PAYLOAD1_HDMI_VIC_MASK	GENMASK(15, 8)
#define DW_HDMI_VSI_PAYLOAD1_HDMI_VIC_OFFSET	8

#define DW_HDMI_PDEC_ACR_CTS			0x0390
#define DW_HDMI_CTS_DECODED_MASK		GENMASK(19, 0)
#define DW_HDMI_CTS_DECODED_OFFSET		0

#define DW_HDMI_PDEC_ACR_N			0x0394
#define DW_HDMI_N_DECODED_MASK			GENMASK(19, 0)
#define DW_HDMI_N_DECODED_OFFSET		0

#define DW_HDMI_PDEC_AVI_HB			0x03a0
#define DW_HDMI_QUANT_RANGE_MASK		GENMASK(31, 30)
#define DW_HDMI_QUANT_RANGE_OFFSET		30
#define DW_HDMI_CONTENT_TYPE_MASK		GENMASK(29, 28)
#define DW_HDMI_CONTENT_TYPE_OFFSET		28
#define DW_HDMI_PIX_REP_FACTOR_MASK		GENMASK(27, 24)
#define DW_HDMI_PIX_REP_FACTOR_OFFSET		24

#define DW_HDMI_PDEC_AVI_PB			0x03a4
#define DW_HDMI_VID_IDENT_CODE_MASK		GENMASK(31, 24)
#define DW_HDMI_VID_IDENT_CODE_OFFSET		24
#define DW_HDMI_IT_CONTENT			BIT(23)
#define DW_HDMI_EXT_COLORIMETRY_MASK		GENMASK(22, 20)
#define DW_HDMI_EXT_COLORIMETRY_OFFSET		20
#define DW_HDMI_RGB_QUANT_RANGE_MASK		GENMASK(19, 18)
#define DW_HDMI_RGB_QUANT_RANGE_OFFSET		18
#define DW_HDMI_NON_UNIF_SCALE_MASK		GENMASK(17, 16)
#define DW_HDMI_NON_UNIF_SCALE_OFFSET		16
#define DW_HDMI_COLORIMETRY_MASK		GENMASK(15, 14)
#define DW_HDMI_COLORIMETRY_OFFSET		14
#define DW_HDMI_PIC_ASPECT_RAT_MASK		GENMASK(13, 12)
#define DW_HDMI_PIC_ASPECT_RAT_OFFSET		12
#define DW_HDMI_ACT_ASPECT_RAT_MASK		GENMASK(11, 8)
#define DW_HDMI_ACT_ASPECT_RAT_OFFSET		8
#define DW_HDMI_VIDEO_FORMAT_MASK		GENMASK(7, 5)
#define DW_HDMI_VIDEO_FORMAT_OFFSET		5
#define DW_HDMI_ACT_INFO_PRESENT		BIT(4)
#define DW_HDMI_BAR_INFO_VALID_MASK		GENMASK(3, 2)
#define DW_HDMI_BAR_INFO_VALID_OFFSET		2
#define DW_HDMI_SCAN_INFO_MASK			GENMASK(1, 0)
#define DW_HDMI_SCAN_INFO_OFFSET		0

#define DW_HDMI_PDEC_AVI_PBLEN			4

#define DW_HDMI_PDEC_AVI_TBB			0x03a8
#define DW_HDMI_PDEC_AVI_LRB			0x03ac
#define DW_HDMI_PDEC_AIF_HB			0x03c4
#define DW_HDMI_PDEC_AIF_PB0			0x03c8

#define DW_HDMI_PDEC_AIF_PB1			0x03cc
#define DW_HDMI_LFE_PLAYBACK_LEVEL_MASK		GENMASK(9, 8)
#define DW_HDMI_LFE_PLAYBACK_LEVEL_OFFSET	8

#define DW_HDMI_PDEC_AIF_PBLEN			2

#define DW_HDMI_PDEC_VSI_ST0			0x3e0
#define DW_HDMI_IEEE_REG_ID_MASK		GENMASK(23, 0)
#define DW_HDMI_IEEE_REG_ID_OFFSET		0

#define DW_HDMI_PDEC_VSI_ST1			0x3e4
#define DW_HDMI_H3D_EXT_DATA_MASK		GENMASK(23, 20)
#define DW_HDMI_H3D_EXT_DATA_OFFSET		20
#define DW_HDMI_H3D_STRUCTURE_MASK		GENMASK(19, 16)
#define DW_HDMI_H3D_STRUCTURE_OFFSET		16
#define DW_HDMI_HDMI_VIC_MASK			GENMASK(15, 8)
#define DW_HDMI_HDMI_VIC_OFFSET			8
#define DW_HDMI_HDMI_VIDEO_FORMAT_MASK		GENMASK(7, 5)
#define DW_HDMI_HDMI_VIDEO_FORMAT_OFFSET	5
#define DW_HDMI_LENGTH_MASK			GENMASK(4, 0)
#define DW_HDMI_LENGTH_OFFSET			0

/* id_cea_video Registers */
#define DW_HDMI_CEAVID_CONFIG			0x400
#define DW_HDMI_CEAVID_RST_MASK			BIT(31)
#define DW_HDMI_CEAVID_RST_OFFSET		31
#define DW_HDMI_CEAVID_YCC422_IPIMAP_MASK	BIT(21)
#define DW_HDMI_CEAVID_YCC422_IPIMAP_OFFSET	21
#define DW_HDMI_CEAVID_YCC420_IPIMAP_MASK	BIT(20)
#define DW_HDMI_CEAVID_YCC420_IPIMAP_OFFSET	20

/* id_hdmi_2_0 Registers */
#define DW_HDMI_HDMI20_CONTROL			0x0800
#define DW_HDMI_VIDDATACHECKEN_MASK		BIT(12)
#define DW_HDMI_VIDDATACHECKEN_OFFSET		12
#define DW_HDMI_DATAISCHECKEN_MASK		BIT(11)
#define DW_HDMI_DATAISCHECKEN_OFFSET		11
#define DW_HDMI_GBCHECKEN_MASK			BIT(10)
#define DW_HDMI_GBCHECKEN_OFFSET		10
#define DW_HDMI_PREAMBCHECKEN_MASK		BIT(9)
#define DW_HDMI_PREAMBCHECKEN_OFFSET		9
#define DW_HDMI_CTRLCHECKEN_MASK		BIT(8)
#define DW_HDMI_CTRLCHECKEN_OFFSET		8

#define DW_HDMI_SCDC_CONFIG			0x0808
#define DW_HDMI_HPDLOW_MASK			BIT(1)
#define DW_HDMI_HPDLOW_OFFSET			1
#define DW_HDMI_POWERPROVIDED_MASK		BIT(0)
#define DW_HDMI_POWERPROVIDED_OFFSET		0

#define DW_HDMI_CHLOCK_CONFIG			0x080c
#define DW_HDMI_MILISECTIMERLIMIT_MASK		GENMASK(15, 0)
#define DW_HDMI_MILISECTIMERLIMIT_OFFSET	0

#define DW_HDMI_HDCP22_CONTROL			0x081c

#define DW_HDMI_SCDC_REGS0			0x0820
#define DW_HDMI_SCDC_SCRAMBSTATUS_MASK		BIT(24)
#define DW_HDMI_SCDC_SCRAMBSTATUS_OFFSET	24
#define DW_HDMI_SCDC_TMDSBITCLKRATIO_MASK	BIT(17)
#define DW_HDMI_SCDC_TMDSBITCLKRATIO_OFFSET	17
#define DW_HDMI_SCDC_SCRAMBEN_MASK		BIT(16)
#define DW_HDMI_SCDC_SCRAMBEN_OFFSET		16

#define DW_HDMI_HDCP22_STATUS			0x08fc

/* id_audio_and_cec_interrupt Registers */
#define DW_HDMI_AUD_CEC_IEN_CLR			0x0f90
#define DW_HDMI_AUD_CEC_IEN_SET			0x0f94

#define DW_HDMI_AUD_CEC_ISTS			0x0f98
#define DW_HDMI_WAKEUPCTRL_ISTS			BIT(22)
#define DW_HDMI_ERROR_FOLL_ISTS			BIT(21)
#define DW_HDMI_ERROR_INIT_ISTS			BIT(20)
#define DW_HDMI_ARBLST_ISTS			BIT(19)
#define DW_HDMI_NACK_ISTS			BIT(18)
#define DW_HDMI_EOM_ISTS			BIT(17)
#define DW_HDMI_DONE_ISTS			BIT(16)
#define DW_HDMI_SCK_STABLE_ISTS			BIT(1)
#define DW_HDMI_CTSN_CNT_ISTS			BIT(0)

#define DW_HDMI_AUD_CEC_IEN			0x0f9c
#define DW_HDMI_AUD_CEC_ICLR			0x0fa0
#define DW_HDMI_AUD_CEC_ISET			0x0fa4

/* id_mode_detection_interrupt Registers */
#define DW_HDMI_MD_IEN_CLR			0x0fc0
#define DW_HDMI_MD_IEN_SET			0x0fc4

#define DW_HDMI_MD_ISTS				0x0fc8
#define DW_HDMI_VOFS_LIN_ISTS			BIT(11)
#define DW_HDMI_VTOT_LIN_ISTS			BIT(10)
#define DW_HDMI_VACT_LIN_ISTS			BIT(9)
#define DW_HDMI_VS_CLK_ISTS			BIT(8)
#define DW_HDMI_VTOT_CLK_ISTS			BIT(7)
#define DW_HDMI_HACT_PIX_ISTS			BIT(6)
#define DW_HDMI_HS_CLK_ISTS			BIT(5)
#define DW_HDMI_HTOT32_CLK_ISTS			BIT(4)
#define DW_HDMI_ILACE_ISTS			BIT(3)
#define DW_HDMI_DE_ACTIVITY_ISTS		BIT(2)
#define DW_HDMI_VS_ACT_ISTS			BIT(1)
#define DW_HDMI_HS_ACT_ISTS			BIT(0)

#define DW_HDMI_MD_IEN				0x0fcc
#define DW_HDMI_MD_ICLR				0x0fd0
#define DW_HDMI_MD_ISET				0x0fd4

/* id_hdmi_interrupt Registers */
#define DW_HDMI_IEN_CLR				0x0fd8
#define DW_HDMI_IEN_SET				0x0fdc

#define DW_HDMI_ISTS				0x0fe0
#define DW_HDMI_I2CMP_ARBLOST_ISTS_ISTS		BIT(30)
#define DW_HDMI_I2CMPNACK_ISTS			BIT(29)
#define DW_HDMI_I2CMPDONE_ISTS			BIT(28)
#define DW_HDMI_VS_THR_REACHED_ISTS		BIT(27)
#define DW_HDMI_VSYNC_ACT_EDGE_ISTS		BIT(26)
#define DW_HDMI_AKSV_RCV_ISTS			BIT(25)
#define DW_HDMI_PLL_CLOCK_GATED_ISTS		BIT(24)
#define DW_HDMI_DESER_MISAL_ISTS		BIT(23)
#define DW_HDMI_CDSENSE_CHG_ISTS		BIT(22)
#define DW_HDMI_CEAVID_EMPTY_ISTS		BIT(21)
#define DW_HDMI_CEAVID_FULL_ISTS		BIT(20)
#define DW_HDMI_SCDCTMDSCFGCHANGE_ISTS_MASK	BIT(19)
#define DW_HDMI_SCDCTMDSCFGCHANGE_ISTS_OFFSET	19
#define DW_HDMI_SCDCSCSTATUSCHANGE_ISTS		BIT(18)
#define DW_HDMI_SCDCCFGCHANGE_ISTS		BIT(17)
#define DW_HDMI_DCM_CURRENT_MODE_CHG_ISTS	BIT(16)
#define DW_HDMI_DCM_PH_DIFF_CNT_OVERFL_ISTS	BIT(15)
#define DW_HDMI_DCM_GCP_ZERO_FIELDS_PASS_ISTS	BIT(14)
#define DW_HDMI_CTL3_CHANGE_ISTS		BIT(13)
#define DW_HDMI_CTL2_CHANGE_ISTS		BIT(12)
#define DW_HDMI_CTL1_CHANGE_ISTS		BIT(11)
#define DW_HDMI_CTL0_CHANGE_ISTS		BIT(10)
#define DW_HDMI_VS_POL_ADJ_ISTS			BIT(9)
#define DW_HDMI_HS_POL_ADJ_ISTS			BIT(8)
#define DW_HDMI_RES_OVERLOAD_ISTS		BIT(7)
#define DW_HDMI_CLK_CHANGE_ISTS			BIT(6)
#define DW_HDMI_PLL_LCK_CHG_ISTS		BIT(5)
#define DW_HDMI_EQGAIN_DONE_ISTS		BIT(4)
#define DW_HDMI_OFFSCAL_DONE_ISTS		BIT(3)
#define DW_HDMI_RESCAL_DONE_ISTS		BIT(2)
#define DW_HDMI_ACT_CHANGE_ISTS			BIT(1)
#define DW_HDMI_STATE_REACHED_ISTS		BIT(0)

#define DW_HDMI_IEN				0x0fe4
#define DW_HDMI_ICLR				0x0fe8
#define DW_HDMI_ISET				0x0fec

/* id_packet_decoder_interrupt Registers */
#define DW_HDMI_PDEC_IEN_CLR			0x0f78
#define DW_HDMI_PDEC_IEN_SET			0x0f7c

#define DW_HDMI_PDEC_ISTS			0x0f80
#define DW_HDMI_DRM_CKS_CHG_ISTS		BIT(31)
#define DW_HDMI_AUD_TYPE_CHG_ISTS		BIT(29)
#define DW_HDMI_VSI_CKS_CHG_ISTS		BIT(27)
#define DW_HDMI_AIF_CKS_CHG_ISTS		BIT(25)
#define DW_HDMI_AVI_CKS_CHG_ISTS		BIT(24)
#define DW_HDMI_ACR_N_CHG_ISTS			BIT(23)
#define DW_HDMI_ACR_CTS_CHG_ISTS		BIT(22)
#define DW_HDMI_GCP_AV_MUTE_CHG_ISTS		BIT(21)
#define DW_HDMI_PD_FIFO_OVERFL_ISTS		BIT(4)
#define DW_HDMI_PD_FIFO_UNDERFL_ISTS		BIT(3)

#define DW_HDMI_PDEC_IEN			0x0f84
#define DW_HDMI_PDEC_ICLR			0x0f88
#define DW_HDMI_PDEC_ISET			0x0f8c

/* id_dmi Registers */
#define DW_HDMI_DMI_SW_RST			0x0ff0
#define DW_HDMI_TMDS_SWRESET			BIT(16)
#define DW_HDMI_HDCP_SWRESET			BIT(8)
#define DW_HDMI_VID_SWRESET			BIT(7)
#define DW_HDMI_PIXEL_SWRESET			BIT(6)
#define DW_HDMI_CEC_SWRESET			BIT(5)
#define DW_HDMI_AUD_SWRESET			BIT(4)
#define DW_HDMI_BUS_SWRESET			BIT(3)
#define DW_HDMI_HDMI_SWRESET			BIT(2)
#define DW_HDMI_MODET_SWRESET			BIT(1)
#define DW_HDMI_MAIN_SWRESET			BIT(0)

#define DW_HDMI_DMI_DISABLE_IF			0x0ff4
#define DW_HDMI_HDMI_ENABLE_MASK		BIT(2)
#define DW_HDMI_HDMI_ENABLE_OFFSET		2

/* id_cec Registers */
#define DW_HDMI_CEC_CTRL			0x1f00
#define DW_HDMI_STANDBY_MASK			BIT(4)
#define DW_HDMI_STANDBY_OFFSET			4
#define DW_HDMI_BC_NACK_MASK			BIT(3)
#define DW_HDMI_BC_NACK_OFFSET			3
#define DW_HDMI_FRAME_TYP_MASK			GENMASK(2, 1)
#define DW_HDMI_FRAME_TYP_OFFSET		1
#define DW_HDMI_SEND_MASK			BIT(0)
#define DW_HDMI_SEND_OFFSET			0

#define DW_HDMI_CEC_MASK			0x1f08
#define DW_HDMI_WAKEUP_MASK			BIT(6)
#define DW_HDMI_WAKEUP_OFFSET			6
#define DW_HDMI_ERROR_FLOW_MASK			BIT(5)
#define DW_HDMI_ERROR_FLOW_OFFSET		5
#define DW_HDMI_ERROR_INITITATOR_MASK		BIT(4)
#define DW_HDMI_ERROR_INITITATOR_OFFSET		4
#define DW_HDMI_ARB_LOST_MASK			BIT(3)
#define DW_HDMI_ARB_LOST_OFFSET			3
#define DW_HDMI_NACK_MASK			BIT(2)
#define DW_HDMI_NACK_OFFSET			2
#define DW_HDMI_EOM_MASK			BIT(1)
#define DW_HDMI_EOM_OFFSET			1
#define DW_HDMI_DONE_MASK			BIT(0)
#define DW_HDMI_DONE_OFFSET			0

#define DW_HDMI_CEC_ADDR_L			0x1f14
#define DW_HDMI_CEC_ADDR_H			0x1f18
#define DW_HDMI_CEC_TX_CNT			0x1f1c
#define DW_HDMI_CEC_RX_CNT			0x1f20
#define DW_HDMI_CEC_TX_DATA(i)			(0x1f40 + ((i) * 4))
#define DW_HDMI_CEC_TX_DATA_MAX			16
#define DW_HDMI_CEC_RX_DATA(i)			(0x1f80 + ((i) * 4))
#define DW_HDMI_CEC_RX_DATA_MAX			16
#define DW_HDMI_CEC_LOCK			0x1fc0
#define DW_HDMI_CEC_WAKEUPCTRL			0x1fc4

/* id_cbus Registers */
#define DW_HDMI_CBUSIOCTRL			0x3020
#define DW_HDMI_DATAPATH_CBUSZ_MASK		BIT(24)
#define DW_HDMI_DATAPATH_CBUSZ_OFFSET		24
#define DW_HDMI_CBUS_SVSRETMODEZ_MASK		BIT(16)
#define DW_HDMI_CBUS_SVSRETMODEZ_OFFSET		16
#define DW_HDMI_CBUS_PDDQ_MASK			BIT(8)
#define DW_HDMI_CBUS_PDDQ_OFFSET		8
#define DW_HDMI_CBUS_RESET_MASK			BIT(0)
#define DW_HDMI_CBUS_RESET_OFFSET		0

/* id_audio Registers */
#define DW_HDMI_AUD_CTRL			0x0200

#define DW_HDMI_AUD_PLL_CTRL			0x0208
#define DW_HDMI_PLL_LOCK_STABLE_MASK		BIT(31)
#define DW_HDMI_PLL_LOCK_STABLE_OFFSET		31

#define DW_HDMI_AUD_FIFO_CTRL			0x0240
#define DW_HDMI_AFIF_INIT_MASK			BIT(0)
#define DW_HDMI_AFIF_INIT_OFFSET		0

#define DW_HDMI_AUD_MUTE_CTRL			0x0258
#define DW_HDMI_AUD_MUTE_SEL_MASK		GENMASK(6, 5)
#define DW_HDMI_AUD_MUTE_SEL_OFFSET		5

#define DW_HDMI_AUD_SAO_CTRL			0x0260
#define DW_HDMI_WS_DISABLE_MASK			BIT(10)
#define DW_HDMI_WS_DISABLE_OFFSET		10
#define DW_HDMI_I2S_32_16_MASK			BIT(0)
#define DW_HDMI_I2S_32_16_OFFSET		0

/* id_audio_fifo_interrupt Registers */
#define DW_HDMI_AUD_FIFO_IEN_CLR		0x0fa8
#define DW_HDMI_AUD_FIFO_IEN_SET		0x0fac

#define DW_HDMI_AUD_FIFO_ISTS			0x0fb0
#define DW_HDMI_AFIF_OVERFL_ISTS		BIT(4)
#define DW_HDMI_AFIF_UNDERFL_ISTS		BIT(3)
#define DW_HDMI_AFIF_THS_PASS_ISTS		BIT(2)
#define DW_HDMI_AFIF_TH_MAX_ISTS		BIT(1)
#define DW_HDMI_AFIF_TH_MIN_ISTS		BIT(0)

#define DW_HDMI_AUD_FIFO_IEN			0x0fb4
#define DW_HDMI_AUD_FIFO_ICLR			0x0fb8
#define DW_HDMI_AUD_FIFO_ISET			0x0fbc

#endif /* __DW_HDMI_RX_H__ */
