/* SPDX-License-Identifier: GPL-2.0-only */
/* Copyright(C) 2016-2020 Intel Corporation. All rights reserved. */

#ifndef __DLB_H
#define __DLB_H

#include <linux/types.h>

enum dlb_error {
	DLB_ST_SUCCESS = 0,
	DLB_ST_DOMAIN_UNAVAILABLE,
	DLB_ST_LDB_PORTS_UNAVAILABLE,
	DLB_ST_DIR_PORTS_UNAVAILABLE,
	DLB_ST_LDB_QUEUES_UNAVAILABLE,
	DLB_ST_LDB_CREDITS_UNAVAILABLE,
	DLB_ST_DIR_CREDITS_UNAVAILABLE,
	DLB_ST_SEQUENCE_NUMBERS_UNAVAILABLE,
	DLB_ST_ATOMIC_INFLIGHTS_UNAVAILABLE,
	DLB_ST_HIST_LIST_ENTRIES_UNAVAILABLE,
	DLB_ST_LDB_PORT_REQUIRED_FOR_LDB_QUEUES,
	DLB_ST_DOMAIN_RESET_FAILED,
	DLB_ST_INVALID_DOMAIN_ID,
	DLB_ST_INVALID_QID_INFLIGHT_ALLOCATION,
	DLB_ST_INVALID_LDB_QUEUE_ID,
	DLB_ST_DOMAIN_NOT_CONFIGURED,
	DLB_ST_INVALID_QID,
	DLB_ST_DOMAIN_STARTED,
	DLB_ST_DIR_QUEUES_UNAVAILABLE,
	DLB_ST_INVALID_PORT_ID,
	DLB_ST_INVALID_LOCK_ID_COMP_LEVEL,
	DLB_ST_NO_MEMORY,
	DLB_ST_INVALID_COS_ID,
	DLB_ST_INVALID_CQ_VIRT_ADDR,
	DLB_ST_INVALID_CQ_DEPTH,
	DLB_ST_INVALID_HIST_LIST_DEPTH,
	DLB_ST_INVALID_DIR_QUEUE_ID,
};
#endif /* __DLB_H */
