/* SPDX-License-Identifier: GPL-2.0 WITH Linux-syscall-note */
#ifndef _UAPI_LINUX_ENCODED_IO_H
#define _UAPI_LINUX_ENCODED_IO_H

#include <linux/types.h>

#define ENCODED_IOV_COMPRESSION_NONE 0
#define ENCODED_IOV_COMPRESSION_BTRFS_ZLIB 1
#define ENCODED_IOV_COMPRESSION_BTRFS_ZSTD 2
#define ENCODED_IOV_COMPRESSION_BTRFS_LZO_4K 3
#define ENCODED_IOV_COMPRESSION_BTRFS_LZO_8K 4
#define ENCODED_IOV_COMPRESSION_BTRFS_LZO_16K 5
#define ENCODED_IOV_COMPRESSION_BTRFS_LZO_32K 6
#define ENCODED_IOV_COMPRESSION_BTRFS_LZO_64K 7
#define ENCODED_IOV_COMPRESSION_TYPES 8

#define ENCODED_IOV_ENCRYPTION_NONE 0
#define ENCODED_IOV_ENCRYPTION_TYPES 1

struct encoded_iov {
	__aligned_u64 len;
	__aligned_u64 unencoded_len;
	__aligned_u64 unencoded_offset;
	__u32 compression;
	__u32 encryption;
};

#define ENCODED_IOV_SIZE_VER0 32

#endif /* _UAPI_LINUX_ENCODED_IO_H */
