# SPDX-License-Identifier: GPL-2.0
#
# Makefile for linux/drivers/platform/x86
# x86 Platform-Specific Drivers
#

intel_pmc_core-y					:= pmc_core.o 
intel_pmc_core_pltdrv-y				:= pmc_core_pltdrv.o
obj-$(CONFIG_INTEL_PMC_CORE)		+= intel_pmc_core_pltdrv.o intel_pmc_core.o
