keembay-cam-objs = keembay-camera.o keembay-pipeline.o \
		      keembay-cam-xlink.o keembay-isp.o \
		      keembay-metadata.o keembay-video.o

obj-$(CONFIG_VIDEO_INTEL_KEEMBAY_CAMERA) += keembay-cam.o
