# SPDX-License-Identifier: GPL-2.0

obj-$(CONFIG_VIDEO_WAVE_VPU) += wave5.o
wave5-objs +=  	vpuapi/wave/wave5.o \
		vpuapi/vpuapi.o \
		vdi/vdi.o \
		v4l2/vpu_dec.o \
		v4l2/vpu.o \
		v4l2/vpu_enc.o

