/* SPDX-License-Identifier: GPL-2.0 */
#ifndef _DT_BINDINGS_INTERRUPT_CONTROLLER_STM32_EXTI_H
#define _DT_BINDINGS_INTERRUPT_CONTROLLER_STM32_EXTI_H

#define STM32_EXTI_TYPE_CONFIGURABLE	0
#define STM32_EXTI_TYPE_DIRECT		1

#define STM32_EXTI_MAPPING_CELL_NB	3

#endif
