#! /bin/bash
# SPDX-License-Identifier: GPL-2.0
# Copyright (c) 2022 YOUR NAME HERE.  All Rights Reserved.
#
# FS QA Test 262
#
# Test the deadlock between qgroup and quota commands
#
. ./common/preamble
_begin_fstest auto qgroup

# Import common functions.
. ./common/filter

# real QA test starts here

# Modify as appropriate.
_supported_fs btrfs

_require_scratch

# Run command that enable/disable quota and create/destroy qgroup asynchronously
qgroup_deadlock_test()
{
	_scratch_mkfs > /dev/null 2>&1
	_scratch_mount
	echo "=== qgroup deadlock test ===" >> $seqres.full

	pids=()
	for ((i = 0; i < 200; i++)); do
		$BTRFS_UTIL_PROG quota enable $SCRATCH_MNT 2>> $seqres.full &
		pids+=($!)
		$BTRFS_UTIL_PROG qgroup create 1/0 $SCRATCH_MNT 2>> $seqres.full &
		pids+=($!)
		$BTRFS_UTIL_PROG qgroup destroy 1/0 $SCRATCH_MNT 2>> $seqres.full &
		pids+=($!)
		$BTRFS_UTIL_PROG quota disable $SCRATCH_MNT 2>> $seqres.full &
		pids+=($!)		
	done

	for pid in "${pids[@]}"; do
		wait $pid
	done

	_scratch_unmount
	_check_scratch_fs
}

qgroup_deadlock_test

# success, all done
echo "Silence is golden"
status=0
exit
