# SPDX-License-Identifier: GPL-2.0+

zhouyi_npu-y := zynpu_core.o zynpu_io.o zynpu_drv.o \
	zynpu_irq.o zynpu_session.o zynpu_job_manager.o \
	zynpu_mm.o zynpu_sysfs.o zynpu_fops.o zhouyi_base.o z1.o z2.o

obj-$(CONFIG_ZYNPU) +=	zhouyi_npu.o
