# SPDX-License-Identifier: GPL-2.0
#
# Copyright (C) Microsoft Corporation. All rights reserved.
#
# Makefile for building the IPE module as part of the kernel tree.
#

obj-$(CONFIG_IPE_PROP_BOOT_VERIFIED) += boot_verified.o
