# SPDX-License-Identifier: GPL-2.0

obj-$(CONFIG_XILINX_PR_DECOUPLER) += pr-decoupler.o
obj-$(CONFIG_FPGA_MGR_XILINX_SPI) += spi.o
obj-$(CONFIG_FPGA_MGR_ZYNQ_FPGA) += zynq-fpga.o
obj-$(CONFIG_FPGA_MGR_ZYNQMP_FPGA) += zynqmp-fpga.o


