# SPDX-License-Identifier: GPL-2.0-only
#
# Makefile for the Realtek USB network device drivers.
#

obj-$(CONFIG_USB_RTL8150)	+= rtl8150.o
obj-$(CONFIG_USB_RTL8152)	+= r8152.o
r8152-objs := r8152_main.o r8152_fw.o
obj-$(CONFIG_USB_RTL8153_ECM)	+= r8153_ecm.o
