# SPDX-License-Identifier: GPL-2.0
#
# Copyright (C) Microsoft Corporation. All rights reserved.
#
# Makefile for building the IPE module as part of the kernel tree.
#

ccflags-y := -I$(srctree)/security/ipe

obj-$(CONFIG_SECURITY_IPE) += \
	default.o \
	policy_header.o \
