# SPDX-License-Identifier: GPL-2.0-only
#
# Makefile for loongson drm drivers.
# This driver provides support for the
# Direct Rendering Infrastructure (DRI)

loongson-y := loongson_connector.o \
	loongson_crtc.o \
	loongson_device.o \
	loongson_drv.o \
	loongson_encoder.o \
	loongson_i2c.o \
	loongson_irq.o \
	loongson_plane.o
obj-$(CONFIG_DRM_LOONGSON) += loongson.o
